stages:

  - stage: terraform
    displayName: Build infrastructure
    jobs:
    - job: Terraform_Plan
      displayName: Terraform Init, Plan & Apply
      pool:
        name: My-AKS-Pool
      steps:
       - task: TerraformTaskV2@2
         inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'AzureDevOpsSP'
            backendAzureRmResourceGroupName: 'AzureDevOps'
            backendAzureRmStorageAccountName: 'storadgeforazuredevops'
            backendAzureRmContainerName: 'terrablobs'
            backendAzureRmKey: 'terraform.tfstate'
       - task: TerraformTaskV2@2
         inputs:
           provider: 'azurerm'
           command: 'plan'
           commandOptions: '-out=tfplan'
           environmentServiceNameAzureRM: 'AzureDevOpsSP'
       - task: TerraformTaskV2@2
         inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: 'tfplan'
            environmentServiceNameAzureRM: 'AzureDevOpsSP'
            
  - stage: BuildApp
    displayName: Build webapp
    jobs:
    - job: buildapp
      displayName: build app
      pool:
        name: Azure Pipelines
        vmImage: 'windows-2019' 
        demands:
         - msbuild
         - visualstudio
          
      steps:
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet 5.8.0'
          inputs:
            versionSpec: 5.8.0
          
        - task: NuGetCommand@2
          displayName: 'NuGet restore'
          inputs:
            restoreSolution: '**\*.sln'
          
        - task: VSBuild@1
          displayName: 'Build solution'
          inputs:
            solution: '**\*.sln'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
            platform: 'any cpu'
            configuration: 'release'
          
        - task: PublishSymbols@1
          displayName: 'Publish symbols path'
          inputs:
            SearchPattern: '**\bin\**\*.pdb'
          continueOnError: true
          
        - task: CopyFiles@2
          displayName: 'Copy Database File'
          inputs:
            Contents: '**\*.dacpac'
            TargetFolder: '$(build.artifactstagingdirectory)'
            flattenFolders: true
          
        - task: PublishBuildArtifacts@1


  - stage: DeployApp
    displayName: Deploy app
    jobs:
    - job: Deployapp
      displayName: Deploy app
      pool:
        vmImage: 'windows-2019' 
      steps:
        - task: AzureRmWebAppDeployment@3
          displayName: 'Deploy Azure App Service'
          inputs:
            azureSubscription: 'Free Subscription(664b98cb-cc33-4ac5-a541-f8cf0203bb97)'
            appType: 'app'
            WebAppName: 'cicdtestwinapp'
            Package: '$(System.DefaultWorkingDirectory)/**/drop'
            WebAppUri: 'webAppUrl'
            TakeAppOfflineFlag: true
            enableXmlVariableSubstitution: true
      