
stages:

- stage: terraform
  displayName: Build infrastructure
  jobs:
  - job: Terraform_Plan
    displayName: Terraform Init, Plan & Apply
    pool:
      name: My-AKS-Pool
    steps:
     - task: TerraformTaskV2@2
       inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'AzureDevOpsSP'
          backendAzureRmResourceGroupName: 'AzureDevOps'
          backendAzureRmStorageAccountName: 'storadgeforazuredevops'
          backendAzureRmContainerName: 'terrablobs'
          backendAzureRmKey: 'terraform.tfstate'
     - task: TerraformTaskV2@2
       inputs:
         provider: 'azurerm'
         command: 'plan'
         commandOptions: '-out=tfplan'
         environmentServiceNameAzureRM: 'AzureDevOpsSP'
     - task: TerraformTaskV2@2
       inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: 'tfplan'
          environmentServiceNameAzureRM: 'AzureDevOpsSP'

      