---
trigger: none
stages:
    - stage: Linter
      displayName: Check the code
      jobs:
      - job: lint
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: docker pull github/super-linter:latest
          displayName: Pull GitHub Super-Linter image
        - script: >-
            docker run \
              -e RUN_LOCAL=true \
              -e VALIDATE_CSHARP=false \
              -e VALIDATE_CPP=false \
              -e VALIDATE_JAVASCRIPT_STANDARD=false \
              -e VALIDATE_JSCPD=false \
              -e VALIDATE_JAVASCRIPT_ES=false \
              -e VALIDATE_CSS=false \
              -e VALIDATE_HTML=false \
              -v $(System.DefaultWorkingDirectory):/tmp/lint \
              github/super-linter
          displayName: 'Run GitHub Super-Linter' 

    - stage: terraform
      displayName: Build infrastructure
      jobs:
      - job: Terraform_Plan
        displayName: Terraform Init, Plan & Apply
        pool:
          name: My-AKS-Pool
        variables:
        - group: Terraform-Variable-Group
        steps:
          - template: terraform.yml
              
    - stage: BuildApp
      displayName: Build webapp
      jobs:
      - job: buildapp
        displayName: build app
        pool:
          name: Azure Pipelines
          vmImage: 'windows-2019' 
          demands:
          - msbuild
          - visualstudio
            
        steps:
          - template: buildapp.yml

    - stage: DeployApp
      displayName: Deploy app
      jobs:
      - job: Deployapp
        displayName: Deploy app
        pool:
          vmImage: 'windows-2019'
        steps:
          - template: deploy.yml